stages:
    - test

variables:
    GO111MODULE: "on"

.test: &test_template
    stage: test
    services:
        - apache/couchdb:2.3.1
    variables:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: abc123
        KIVIK_TEST_DSN: http://admin:abc123@apache-couchdb:5984/
    before_script:
        - curl --silent --fail -o /dev/null -X PUT ${KIVIK_TEST_DSN}/_users
        - curl --silent --fail -o /dev/null -X PUT ${KIVIK_TEST_DSN}/_replicator
        - curl --silent --fail -o /dev/null -X PUT ${KIVIK_TEST_DSN}/_global_changes
        - curl --silent --fail -o /dev/null -X PUT ${KIVIK_TEST_DSN}/_node/nonode@nohost/_config/replicator/interval -d '"1000"'
    script:
        - go test -race -tags=livetest ./...

lint:
    stage: test
    image: golangci/golangci-lint:v1.30
    script:
        - go mod download
        - golangci-lint run ./...
        - ./script/check-license.sh

coverage:
    stage: test
    image: golang:1.15
    script:
        - ./script/coverage.sh

go-1.14:
    <<: *test_template
    image: golang:1.14

go-1.15:
    <<: *test_template
    image: golang:1.15

go-rc:
    <<: *test_template
    image: golang:rc
    allow_failure: true
