stages:
    - test

variables:
    GO111MODULE: "on"

.test: &test_template
    stage: test
    services:
        - apache/couchdb:2.3.1
    variables:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: abc123
        KIVIK_TEST_DSN: http://admin:abc123@apache-couchdb:5984/
    before_script:
        - curl --silent --fail -o /dev/null -X PUT ${KIVIK_TEST_DSN}/_users
        - curl --silent --fail -o /dev/null -X PUT ${KIVIK_TEST_DSN}/_replicator
        - curl --silent --fail -o /dev/null -X PUT ${KIVIK_TEST_DSN}/_global_changes
        - curl --silent --fail -o /dev/null -X PUT ${KIVIK_TEST_DSN}/_node/nonode@nohost/_config/replicator/interval -d '"1000"'
    script:
        - go test -race -tags=livetest ./...

lint:
    stage: test
    image: golang:1.13
    script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.22.2
        - go mod download
        - golangci-lint run ./...

coverage:
    stage: test
    image: golang:1.13
    script:
        - ./script/coverage.sh

go-1.11:
    <<: *test_template
    stage: test
    image: golang:1.11

go-1.12:
    <<: *test_template
    stage: test
    image: golang:1.12

go-1.13:
    <<: *test_template
    stage: test
    image: golang:1.13

go-rc:
    <<: *test_template
    stage: test
    image: golang:rc
    allow_failure: true
