before:
  hooks:
  - go mod download
  # - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  id: kouchctl
  goos:
  - linux
  - windows
  - darwin
  main: ./cmd/kouchctl
  binary: kouchctl
archives:
- format: tar.gz
  name_template: "kouchctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
release:
  github:
    owner: go-kivik
    name: xkivik
  prerelease: auto
