name: Trigger GitLab release
on:
  create:
    tags:
    - v*
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Job
      uses: appleboy/gitlab-ci-action@v0.0.2
      with:
        token: ${{ secrets.GITLAB_TOKEN }}
        project_id: 13151405
