name: Trigger GitLab release
on:
  create:
    tags:
    - v*
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Job
      uses: appleboy/gitlab-ci-action@v0.0.2
      with:
        token: ${{ secrets.GITLAB_CI_TRIGGER_TOKEN }}
        project_id: 13151405
